import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import InstallBootstrap from "./components/InstallBootstrap";
import Link from 'next/link';

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body className="min-h-screen bg-gray-900 text-white">
        <header className="navbar">
          <nav className="navbar-links">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
            <Link href="/agents">Agents</Link>
          </nav>
        </header>
        <InstallBootstrap />
        <div className="container min-h-screen flex flex-col justify-center items-center">
          {children}
        </div>
      </body>
    </html>
  );
}
