
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import InstallBootstrap from "./components/InstallBootstrap";
import Link from 'next/link';


export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"> 
      <body style = {{backgroundColor: "#222222"}}>
        <header style={{ backgroundColor: "#007bff", padding: "1rem", borderBottom: "1px solid #444"}}>
          <nav style={{ display: "flex", gap: "1rem" }}>
            <Link href="/" style={{fontSize: "1.25rem", color: "white" }}>Home</Link>
            <Link href="/about" style={{fontSize: "1.25rem", color: "white" }}>About</Link>
            <Link href="/agents" style={{fontSize: "1.25rem", color: "white" }}>Agents</Link>
          </nav>
        </header>
        <InstallBootstrap/>
        {children}
      </body>
    </html>
  );
}
